# Generated by Django 4.0 on 2022-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
